import DashboardSidebar from "@/components/dashboard/layout/sidebar";
import "../globals.css";
import DashboardMainSide from "@/components/dashboard/layout/mainSide";
import MainSideHead from "@/components/dashboard/layout/mainSIdeHead";
import { Suspense } from "react";
import Tostify from "@/components/tostify";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
const getData=async ()=>{
  const cook=cookies();
  const result=await fetch(`https://distracted-mcnulty-orq2ubkyw.liara.run/api/get-user-admin-data/`,{headers:{auth:cook.get('auth').value}});
  const data=await result.json();
  if(!data._id){
    redirect("/myacount")
  }
    return data;
  

}
export default async function RootLayout({ children }) {
  const cook=cookies();
  if(!cook.get('auth')){
    redirect('/')
  }
  const data=await getData();
  return (
    <html lang="fa" dir="rtl">
      <body className="bg-gray-100 min-h-screen w-full">
        <div className="grid grid-cols-6  min-h-screen h-full">
          <div className="col-span-1 bg-gray-700">
            {/* ---right side ----*/}
            <DashboardSidebar />
          </div>

          <div className="col-span-5">
            {/* ---mina side---  */}

            <MainSideHead />

            <DashboardMainSide>{children}</DashboardMainSide>
          </div>
       
        </div>
        <Tostify />
      </body>
    </html>
  );
}
